### ISSUE TITLE
Refine doc & code

### ISSUE THREAD

**Issue by minghu6** [sysprog21/lkmpg#158]
1. Move the confusing note about `struct proc_ops` replacing with `struct file_operations` on linux >=5.6:
https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/lkmpg.tex#L957-L990
The `struct proc_ops` would replace the `struct file-operations` only when create proc  releated defined on <linux/proc_fs.h>
In other word, regist device doesn't be affected, still using `struct file_operations`. It's confusing write this note above the regist device code (FOE ME, I HAVE SPENT PLENTY OF TIME ON SEARCHING HOW TO REGIST DEVICE USING STRUCT PROC_OPS)
I highly recommend to move this note down to next code example which replacing takes place truely!

2.  https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/chardev.c#L25-L39
The msg char array should be declared with length of `BUF_LEN + 1` since `BUF_LEN` is max length of message.

3. https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/chardev.c#L152
On `device_write`, It's prefered to use `EOPNOTSUPP` instead of `EINVAL` since the former raises unsupported error, the latter raises invalid argument.

4. Improve read/write fucntion code among `fsproc{1-3}.c`:
https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/procfs3.c#L23-L40
https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/procfs3.c#L41-L53

These code are a little wired and far from decent, the parameter `loff_t *` is ignored incorrectly and so the behavior is quite different from normal read/write.I've reimplemented read/write code, here is full code:

```c
#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/proc_fs.h>
#include <linux/uaccess.h>
#include <linux/version.h>
// #include <linux/slab.h>  // kmalloc etc.

/* Header */
#define do_sslice(news, s, n) for(int i=0;i<n;++i) { news[i]=s[i]; };news[n]='\0';

#define proc_name "hello"
#define PROC_BUF_CAP (size_t)1024

static ssize_t proc_read(struct file *filp, char __user *buffer, size_t size,
                         loff_t *offset);
static ssize_t proc_write(struct file *filp, const char __user *buffer,
                          size_t size, loff_t *offset);
static int proc_open(struct inode *, struct file*);
static int proc_close(struct inode *, struct file*);


/* Source */

#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 6, 0)
/// @brief Since Linux 5.6, or else use file_operations on <linux/fs.h> instead
/// for older version
static struct proc_ops proc_ops = {
    .proc_read = proc_read,
    .proc_write = proc_write,
    .proc_open = proc_open,
    .proc_release = proc_close,
};
#else
#include <linux/fs.h>
static struct file_operations proc_ops = {
    .read = proc_read,
    .write = proc_write,
};
#endif

static struct proc_dir_entry *proc_file;
static char proc_buf[PROC_BUF_CAP + 1];
static char helper_buf[PROC_BUF_CAP + 1];


static ssize_t proc_read(struct file *filp, char __user *buffer, size_t size,
                         loff_t *offset) {

    static char *s = "ALOHO!";
    size_t slen = strlen(s) + 1;

    size_t actual_read;

    if (*offset >= slen) {
        pr_info("copy to user finished.");
        return 0;
    }

    if (copy_to_user(buffer, s+*offset,
                     (actual_read = min(size, (size_t)(slen - *offset))))) {
        pr_err("copy to user failed!");
        return -EFAULT;
    }

    pr_info("read /proc/%s\n", filp->f_path.dentry->d_name.name);
    *offset += actual_read;

    return actual_read;
}


static ssize_t proc_write(struct file *filp, const char __user *buffer,
                          size_t size, loff_t *offset) {
    size_t actual_write = min(size, PROC_BUF_CAP-(size_t)*offset);
    static char slice[PROC_BUF_CAP];

    if (filp->f_flags & O_APPEND) {
        return -EOPNOTSUPP;
    }

    if (*offset >= PROC_BUF_CAP) {
        pr_info("write to end.");
        return 0;
    }

    if (copy_from_user(proc_buf + *offset, buffer, actual_write)) {
        pr_err("copy from user failed!");
        return -EFAULT;
    }

    *offset += actual_write;

    do_sslice(helper_buf, proc_buf, *offset);
    pr_info("write to %s\n", helper_buf);

    return actual_write;
}


static int proc_open(struct inode *inode, struct file* filp) {
    try_module_get(THIS_MODULE);
    return 0;
}


static int proc_close(struct inode *inode, struct file* filp) {
    module_put(THIS_MODULE);
    return 0;
}


static int __init proc_init(void) {
    if (!(proc_file = proc_create(proc_name, 0644, NULL, &proc_ops))) {
        proc_remove(proc_file);
        pr_alert("Error: couldn't init /proc/%s\n", proc_name);
        return -ENOMEM;
    }

    pr_info("/proc/%s\n", proc_name);
    return 0;
}

static void __exit proc_exit(void) {
    proc_remove(proc_file);
    pr_info("/proc/%s removed\n", proc_name);
}

module_init(proc_init);
module_exit(proc_exit);

MODULE_LICENSE("GPL");

```
It need more modern c standard config than C90, for example `ccflags-y += -std=gnu17`.

**Comment by minghu6** [comment]
5. Unmached code and comment
https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/print_string.c#L44-L#56
`"\015\012"` is `\v\b` rather than CRLF `\r\n`.

**Comment by linD026** [comment]
Hi @minghu6 , 
Sorry for the late to reply.

> 1. Move the confusing note about `struct proc_ops` replacing with `struct file_operations` on linux >=5.6:
>    https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/lkmpg.tex#L957-L990
>    
>    The `struct proc_ops` would replace the `struct file-operations` only when create proc  releated defined on <linux/proc_fs.h>
>    In other word, regist device doesn't be affected, still using `struct file_operations`. It's confusing write this note above the regist device code (FOE ME, I HAVE SPENT PLENTY OF TIME ON SEARCHING HOW TO REGIST DEVICE USING STRUCT PROC_OPS)
>    I highly recommend to move this note down to next code example which replacing takes place truely!

Yes, it won't affect the registering of the device, but the paragraph here actually talks about the file operation. And, it seems like the file operation will be related to the proc_ops. So, I think the description of proc_ops replacing the file_ops is still needed in the section here.
But still, it might confuse others. So, I will add more sentences to hint that this description talks about the file_ops and proc_ops rather than registering the device.

> 2. https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/chardev.c#L25-L39
>    
>    The msg char array should be declared with length of `BUF_LEN + 1` since `BUF_LEN` is max length of message.

The macro, `BUF_LEN`, is the length of the buffer, not the message length.
So, I think there doesn't need to change.

> 3. https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/chardev.c#L152
>    
>    On `device_write`, It's prefered to use `EOPNOTSUPP` instead of `EINVAL` since the former raises unsupported error, the latter raises invalid argument.

Yes, it should uses the `EOPNOTSUPP`.
Thanks.

> 4. Improve read/write fucntion code among `fsproc{1-3}.c`:
>    https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/procfs3.c#L23-L40
>    
>    https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/procfs3.c#L41-L53
> 
> These code are a little wired and far from decent, the parameter `loff_t *` is ignored incorrectly and so the behavior is quite different from normal read/write.I've reimplemented read/write code, here is full code:
> 
> It need more modern c standard config than C90, for example `ccflags-y += -std=gnu17`.

The read/write functions are a little weird. I will modify them.
For using modern C standards, we need to consider more.
Since kernel version v5.18, especially after this commit ["Kbuild: move to -std=gnu11"](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/Makefile?h=v6.0-rc4&id=e8c07082a810fbb9db303a2b66b66b8d7e588b53), kernel supports C11 features. We have the option to move to it.
But considering LKMPG is supporting the v5.x version, we must stick to the C89 still a while.
However, for C17, it might be the wrong standard to use.

**Comment by linD026** [comment]
> 5. Unmached code and comment
>    https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/print_string.c#L44-L56
>    
>    `"\015\012"` is `\v\b` rather than CRLF `\r\n`.

The `"\015\012"` seems correct.
According to [the ASCII table](https://en.cppreference.com/w/cpp/language/ascii), `CR` is `015` and `LF` is `012`.
And, `\v\b` is `\013\010`.
I might be wrong, please provide more information about this.

Thanks

**Comment by linD026** [comment]
> > 3. https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/chardev.c#L152
> >    
> >    On `device_write`, It's prefered to use `EOPNOTSUPP` instead of `EINVAL` since the former raises unsupported error, the latter raises invalid argument.
> 
> Yes, it should uses the `EOPNOTSUPP`. Thanks.

Sorry, I recheck the write man page to make sure that the change here is suitable to the definition.
In the man page, it doesn't have any error value that is `EOPNOTSUPP`, `NOTSUPP`, or even `NOTSUPP` (kernel defined).
And from the description of `EINVAL` in the manual:

```
EINVAL **fd is attached to an object which is unsuitable for
       writing**; or the file was opened with the O_DIRECT flag,
       and either the address specified in buf, the value
       specified in count, or the file offset is not suitably
       aligned.
```

The `EINVAL` is correct.

**Comment by linD026** [comment]
> > 2. https://github.com/sysprog21/lkmpg/blob/637e707a1ab7efa62234a374c62ffb040800aca8/examples/chardev.c#L25-L39
> >    
> >    The msg char array should be declared with length of `BUF_LEN + 1` since `BUF_LEN` is max length of message.
> 
> The macro, `BUF_LEN`, is the length of the buffer, not the message length. So, I think there doesn't need to change.

Oops, I saw the comments.
Sorry again. But I still don't think that we should change here.
The method we measure the length of the message includes the '\0' which I think that it s why you suggest that it needs to add one more byte.

**Comment by jserv** [comment]
Ready to close?

**Comment by linD026** [comment]
Sure, I think.
If there are any other opinions we can just reopen it.
