### ISSUE TITLE
Suggest to move code snippets to avoid confusion in Chapter 2

### ISSUE THREAD

**Issue by lisanhu** [sysprog21/lkmpg#185]
Thanks for your work! It's a great read!

Chapter 2 basically says how to retrieve kernel headers on Debian/Ubuntu and Arch system.

However, the code snippets are not in a good order which may result in confusion of the reader.
The 1st one is about searching the header package in Debian/Ubuntu:
```
sudo apt-get update
apt-cache search linux-headers-`uname -r`
```
The 2nd snippet is about installing linux-headers package on Arch Linux.

The 3rd code snippet has a description "This will tell you what kernel header files are available. Then for example:":
```
sudo apt-get install kmod linux-headers-5.4.0-80-generic
```

The description text and the 3rd code snippet should follow the 1st one.

**Comment by linD026** [comment]
Hi,
Yeah, it's a little bit weird. ;)
I will fix this.
Thanks.
