### ISSUE TITLE
procfs1.ko runtime investigation

### ISSUE THREAD

**Issue by tclee060219sat** [sysprog21/lkmpg#192]
Shown below is my procfs1.ko runtime investigation.  It shows `cat /proc/helloworld` runs only once but `procfile_read()` in `procfs1.c` is called twice. I am interested in knowing why `procfile_read()` is called twice for one run of `cat /proc/helloworld`. Comment please.
```
lkmpg/examples$ make && ../scripts/kernel-module-exercise.sh procfs1
[...]
rmmod: ERROR: Module procfs1 is not currently loaded
-----@21 module_remove() procfs1 unloading failure
-----@46 $pstr ==
-----@48 loading success
Terminal 2 (/dev/pts/4)
$ cat /proc/helloworld 
HelloWorld!
-----@19 module_remove() procfs1 unloading success
3月 23 11:04:38 tclee-VivoBook-12-ASUS-Laptop-E203MAS-E203MA kernel: /proc/helloworld created
3月 23 11:04:47 tclee-VivoBook-12-ASUS-Laptop-E203MAS-E203MA kernel: procfile read helloworld
3月 23 11:04:47 tclee-VivoBook-12-ASUS-Laptop-E203MAS-E203MA kernel: copy_to_user failed
3月 23 11:04:57 tclee-VivoBook-12-ASUS-Laptop-E203MAS-E203MA kernel: /proc/helloworld removed
```

**Comment by jserv** [comment]
The messages above have been condensed. I defer to @linD026 .

**Comment by linD026** [comment]
This question is already answered in the  `/proc File System` chapter:

> Every time the file /proc/helloworld is read, the function procfile_read is called. Two parameters of this function are very important: the buffer (the second parameter) and the offset (the fourth one). The content of the buffer will be returned to the application which read it (for example the cat command). The offset is the current position in the file. If the return value of the function is not null, then this function is called again. So be careful with this function, if it never returns zero, the read function is called endlessly.

So, the first time it will read the buffer which is "HelloWorld!", then add `len` to `offset` and return a non-zero value to indicate the file system calls the function again. The second time, the condition check of `offset` will let the function return a zero value so it won't be called again.
This is why `procfile_read()` is called twice.
