### ISSUE TITLE
procfs2.c vs. procfs3.c

### ISSUE THREAD

**Issue by tclee060219sat** [sysprog21/lkmpg#196]
The procfs3.c procfs_read()'s parameters are identical to the procfs2.c procfile_read(). Running the same catnonblock app, the former gives nothing back to the app while the latter fills its internal buffer content to the app. I do no know the reason for the different implementations of those two functions. 
Comment please.

**Comment by jserv** [comment]
> The procfs3.c procfs_read()'s parameters are identical to the procfs2.c procfile_read().

You can simply run `diff -up examples/procfs2.c examples/procfs3.c` and figure out the incremental changes that this book intentionally addressed for the sake of kernel APIs. 

Next time, don't say "Comment please." Instead, improve your message body. It is more polite to provide informative descriptions.
