### ISSUE TITLE
11.1 Sleep chapter. API module_interruptible_sleep_on

### ISSUE THREAD

**Issue by acollamati** [sysprog21/lkmpg#197]
I think that in the Latex file 
**module_interruptible_sleep_on** should be replaced with **wait_event_interruptible** and
**module_sleep_on** with **wait_event**
Regards

**Comment by linD026** [comment]
Hi @acollamati ,
Yeah, it seems like we missed replacing the `module_interruptible_sleep_on ` and `module_sleep_on ` with the `wait_event_interruptible ` and `wait_event` respectively.
Thanks for the report.
