### ISSUE TITLE
Smatch repository is unavailable

### ISSUE THREAD

**Issue by linD026** [sysprog21/lkmpg#201]
The Smatch repository is unavailable to access.
Should we switch to downloading [the GitHub repo](https://github.com/error27/smatch) instead of using the `https://repo.or.cz/smatch.git`, or report the bug to the Smatch mailing list and wait for it to be fixed?
I prefer the former approach and will wait a few days to see if the issue is resolved or not.

**Comment by jserv** [comment]
I prefer the migration to GitHub since the [official mirror](https://lore.kernel.org/all/20220810105926.GS3460@kadam/) exists.
