### ISSUE TITLE
Build kernel module for Rpi3MB

### ISSUE THREAD

**Issue by tclee060219sat** [sysprog21/lkmpg#203]
FYI, I just figured out a method which builds the kernel module for the RPi 3B board running kernel buildroot 5.10.1-v7. Listed below is the module I built:
```
$ file Simplest.ko
Simplest.ko: ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), BuildID[sha1]=f343bdba0b4d422f841f54183d6196a970bd1f30, with debug_info, not stripped
```

Using this method I am going to exercise all the lkmpg modules on the above RPi 3B board, offloading the burden of my Asus laptop running Ubuntu 22.04 LTS.

**Comment by jserv** [comment]
Thanks for confirming the generation of armhf based modules.
