### ISSUE TITLE
lkmpg on RpiOsLite/rpi3MB

### ISSUE THREAD

**Issue by tclee060219sat** [sysprog21/lkmpg#205]
FYI, the lkmpg/examples/make execution failed in the building four .ko files listed below. I suspend the resolution of the failures and move on the good .ko files.

tclee@raspberrypi:~/jun08thu23/lkmpg/examples $ egrep jun08 Makefile
# jun08thu23 obj-m += procfs3.o
# jun08thue23 obj-m += kbleds.o
# jun08thu23 obj-m += chardev2.o
# jun08thu23 obj-m += syscall.o
tclee@raspberrypi:~/jun08thu23/lkmpg/examples $

**Comment by jserv** [comment]
> FYI, the lkmpg/examples/make execution failed in the building four .ko files listed below. I suspend the resolution of the failures and move on the good .ko files.

Please improve your wring for more informative bug reports.
