### ISSUE TITLE
Consistent usage of __init and __exit

### ISSUE THREAD

**Issue by samuelerickson977** [sysprog21/lkmpg#207]
I have noticed that not all of the kernel module examples use __init or __exit. Is there a reason for this? I understand the purpose of __init and __exit macros, but I am rather just asking if this was an oversight or on purpose.

**Comment by linD026** [comment]
Hi @samuelerickson977 ,
Most examples have the __init and __exit, and we should have those macros. I think we just missed them for some newly added examples.
Thanks for the report, I will add them ASAP.
