### ISSUE TITLE
The package xparse should be include in tex file

### ISSUE THREAD

**Issue by Hsins** [sysprog21/lkmpg#30]
Macros defined with `\NewDocumentCommand` are robust and the "LaTeX 3" team marked it as "stable". The command `\samplec` is defined with it in [`lib/codeblock.tex`](https://github.com/sysprog21/lkmpg/blob/master/lib/codeblock.tex) and reported as "error" by pdflatex engine because we use `\NewDocumentCommand` without `\usepackage{xparse}`.

This may cause things to work incorrectly when compiling documents on several platform.

**Comment by jserv** [comment]
Close via commit d097d0c
