### ISSUE TITLE
Design new book covers

### ISSUE THREAD

**Issue by jserv** [sysprog21/lkmpg#4]
It has been 16 years since last book cover for "[The Linux Kernel Module Programming Guide](https://tldp.org/LDP/lkmpg/2.6/lkmpg.pdf)". We would change the cover sooner or later.

Candidate cover:
![0-linux-kernel-module](https://user-images.githubusercontent.com/478921/126746681-cf825c8b-0202-4929-a838-6ce970bb1302.png)

**Comment by bitter-bits** [comment]
This one is a similiar design, with unified font type and new house:
![image](https://raw.githubusercontent.com/bitter-bits/linux2021-quiz/main/2021-07-24_142554.png)

**Comment by bitter-bits** [comment]
This one is a similiar design, with unified font type and new house:
![image](https://raw.githubusercontent.com/bitter-bits/linux2021-quiz/main/2021-07-24_150546x0.5.png)

[Full size](https://raw.githubusercontent.com/bitter-bits/linux2021-quiz/main/2021-07-24_150546.png)

**Comment by jserv** [comment]
Thank @bitter-bits and @jkrvivian for contributing! The cover page is landed.
