### ISSUE TITLE
Add website link to repository details.

### ISSUE THREAD

**Issue by Hsins** [sysprog21/lkmpg#41]
Since that we can access the book via [https://sysprog21.github.io/lkmpg/](https://sysprog21.github.io/lkmpg/), it's nice to show that link in repository details:

![image](https://user-images.githubusercontent.com/26391143/128298591-dea1a967-c8cf-4953-836f-a2c5eb6be03d.png)

Just clicking the gear button on the top-right corner and enter the URL in the field of "website".

**Comment by jserv** [comment]
Thanks for reminder. I have configured.
