### ISSUE TITLE
Small indentation problem in 0.4.4

### ISSUE THREAD

**Issue by FantasqueX** [sysprog21/lkmpg#44]
![image](https://user-images.githubusercontent.com/46747123/128371612-51da51f6-fc9b-4e97-a3c7-44cdc1634eae.png)

This is a code snippet from hello-4.c. I think the line number should be right aligned, and code should be left aligned, but I'm not familiar with TeX 

Really love this project and look forward to a fix.

**Comment by Hsins** [comment]
Edit [`html.cfg`](https://github.com/sysprog21/lkmpg/blob/master/html.cfg) file by adding following line:

```diff
\Css{.ecrm-0500 { 
    font-size: 70\%;
    font-style: italic; 
    color: gray;
+   width: 1.5rem;
+   display: inline-block; 
    -webkit-user-select: none;
    -moz-user-select: none;
    -o-user-select: none;
    user-select: none;
}}
```
