### ISSUE TITLE
The `proc_ops` structure should be `file_operations`.

### ISSUE THREAD

**Issue by asas1asas200** [sysprog21/lkmpg#6]
Chapter 0.6.1 introduce the `proc_ops` structure and it says that it is defined in `/urs/include/linux/fs.h`, but the `fs.h` never defines this structure since kernel 2.6.12rc2 according to this:
https://github.com/torvalds/linux/blame/master/include/linux/fs.h#L2022
According to the above, I think this structure should be `file_operations`.

I also find the `proc_ops` structure in this:
https://github.com/torvalds/linux/commit/d56c0d45f0e27f814e87a1676b6bdccccbc252e9
It applied since kernel 5.6-rc1 to improve VFS performance.

**Comment by jserv** [comment]
Good. Please send pull request(s) for API transition.
