### ISSUE TITLE
MODULE_SUPPORTED_DEVICE removed 

### ISSUE THREAD

**Issue by nlantau** [sysprog21/lkmpg#61]
In section [0.4.4 Licensing and Module Documentation](https://sysprog21.github.io/lkmpg/#licensing-and-module-documentation) the code of **hello-4.c** uses 
```c
MODULE_LICENSE("GPL"); 
MODULE_AUTHOR("LKMPG"); 
MODULE_DESCRIPTION("A sample driver"); 
MODULE_SUPPORTED_DEVICE("testdevice"); 
```
where **MODULE_SUPPORTED_DEVICE** is remove from upstream since [March 17, 2021](https://github.com/torvalds/linux/commit/6417f03132a6952cd17ddd8eaddbac92b61b17e0#diff-1a8b5118e6eaf5be44fdf51f9bceaf816aec6d96e4a048b8455bcfbca6a680f2).

**Comment by jserv** [comment]
Thank @nlantau for pointing this out!

**Comment by nlantau** [comment]
> Thank @nlantau for pointing this out!

No worries! Thanks for a great guide!
