### ISSUE TITLE
Mention PDF download information in generated HTML

### ISSUE THREAD

**Issue by jserv** [sysprog21/lkmpg#64]
At present, HTML is rendered via `make4ht`. However, it lacks the information about PDF downloading.

The expected output:
1. Change the HTML template and/or setting to add the PDF download hyperlink.
2. Mention PDF download only in generated HTML. The body of PDF document should not contain the download link though.

**Comment by fennecJ** [comment]
I come up with 2 solutions for this issue
* 1 We can add
  ```
  \begin{center}
  \href{https://github.com/sysprog21/lkmpg/releases/download/latest/lkmpg.pdf}{Download this page in pdf}
  \end{center}
  ```
  At the end of `html.cfg`, and the information about PDF downloading can only be at the top of the page:
  ![image](https://user-images.githubusercontent.com/58484289/129660772-69928f4b-045b-4cdd-956b-bc4c9295b296.png)

* 2 Using \ifdefined\HCode
  By this way we can choose where to place the information about PDF downloading.
  ![image](https://user-images.githubusercontent.com/58484289/129661405-2cd77704-22f8-46e1-9b78-b697090acd8d.png)

**Comment by jserv** [comment]
How about following [Yocto Project Overview and Concepts Manual](http://docs.yoctoproject.org/overview-manual/)? We can put the hyperlinks to PDF download and GitHub  in the upper right corner of the HTML page.

**Comment by fennecJ** [comment]
Add following code
```diff
--- a/html.cfg
+++ b/html.cfg
@@ -45,5 +45,15 @@
     user-select: none;
 }}
 
+\Css{.flushright:first-child {
+    position:absolute;
+    top:0;
+    right:0;
+}}
+
 \begin{document}
 \EndPreamble
+
+\begin{flushright}
+\href{https://github.com/sysprog21/lkmpg/releases/download/latest/lkmpg.pdf}{Download this page in pdf}
+\end{flushright}
```
into `html.cfg` would be looked like:
![image](https://user-images.githubusercontent.com/58484289/129674515-6d2fd051-fc31-4c3b-83a4-78eb58bf5232.png)

You can check it in [https://fennecj.github.io/lkmpg/](https://fennecj.github.io/lkmpg/)

**Comment by jserv** [comment]
Change from "Download this page in pdf" to "Download PDF document"

**Comment by jserv** [comment]
> You can check it in https://fennecj.github.io/lkmpg/

Can you reserve some spaces at the end of the line "Download PDF document"?

**Comment by fennecJ** [comment]
Did you mean something looks like this?
![image](https://user-images.githubusercontent.com/58484289/129695186-4b429a3a-136e-4c6c-9dad-b6f57eeff4a7.png)
You can modify the space between word and right side through `right` value, and modifiy the space between word and top side through `top` value.
```diff
+\Css{.flushright:first-child {
+    position:absolute;
+    top: 10px;
+    right: 50px;
+}}
+
```

**Comment by jserv** [comment]
> You can modify the space between word and right side through `right` value, and modifiy the space between word and top side through `top` value.

It looks great to me. Please send the corresponding pull request.
