### ISSUE TITLE
Update Acknowledgements

### ISSUE THREAD

**Issue by jserv** [sysprog21/lkmpg#68]
The current "Acknowledgements" section is not up to date. We can generate the new list of contributions by looking up git log. The command `git shortlog examples lkmpg.tex` works out of the box.

However, we might need extra table to convert GitHub account into the names in Pinyin.

**Comment by jserv** [comment]
A good example is [The Not So Short Introduction to LATEX 2ε](https://tobi.oetiker.ch/lshort/lshort.pdf)
source: https://github.com/oetiker/lshort/blob/master/book/src/contrib.tex

**Comment by jserv** [comment]
Since we have received the contributions from individuals, it is time to update acknowledgement list. Preliminary steps:
1. Create a new TeX document, `contrib.tex`, which preserves the names and email address in alphabetical order.
2. Include `contrib.tex` in section "Acknowledgements"
3. Ensure each contributor is listed within compact layout.

**Comment by fennecJ** [comment]
I manage to write a [script](https://github.com/fennecJ/lkmpg/blob/master/.ci/gen-contributor-list.sh) to generate the contributors' list and parse the output into [contrib.tex](https://github.com/fennecJ/lkmpg/blob/master/lib/contrib.tex)
However, some contributors are duplicated due to different email addresses they use:
![image](https://user-images.githubusercontent.com/58484289/134803670-ce04d3a2-fd21-4af5-a7e1-4334b093ba16.png)

This can be solved via configuring `.mailmap` manually, but I don't know which email is their main email.

Currently the output can be checked in here:
https://fennecj.github.io/lkmpg/#acknowledgements

**Comment by linD026** [comment]
We can open the new issue or use the current one to tell the contributor to give us their main email.
By the way, my main email is `shiyn.lin@gmail.com`. And the `linzhien` is also my sub-account.
Thanks.

**Comment by jserv** [comment]
> I manage to write a [script](https://github.com/fennecJ/lkmpg/blob/master/.ci/gen-contributor-list.sh) to generate the contributors' list and parse the output into [contrib.tex](https://github.com/fennecJ/lkmpg/blob/master/lib/contrib.tex)
> However, some contributors are duplicated due to different email addresses they use:

You can prepare the script(s) in directory `scripts/`, which is intended for maintenance purpose. The format of contributor list can be as following:
# Name (to be listed in LKMPG) # Hanyu Pinyin # email-1 # email-2 # remark

Take me for example,
```
Jim Huang, Ching-Chun Huang, jserv.tw@gmail.com, jserv@ccns.ncku.edu.tw, jserv@biilabs.io
```

Then, we can make use of `grep` to see if the contributor was already listed or not.

**Comment by jserv** [comment]
> > I manage to write a [script](https://github.com/fennecJ/lkmpg/blob/master/.ci/gen-contributor-list.sh) to generate the contributors' list and parse the output into [contrib.tex](https://github.com/fennecJ/lkmpg/blob/master/lib/contrib.tex)
> > However, some contributors are duplicated due to different email addresses they use:
> 
> You can prepare the script(s) in directory `scripts/`, which is intended for maintenance purpose. The format of contributor list can be as following:
> 
> ```
> Name (to be listed in LKMPG), Hanyu Pinyin, email-1, email-2, remark
> ```
> 
> Take me for example,
> 
> ```
> Jim Huang, Ching-Chun Huang, jserv.tw@gmail.com, jserv@ccns.ncku.edu.tw, jserv@biilabs.io
> ```
> 
> Then, we can make use of `grep` to see if the contributor was already listed or not.

**Comment by jserv** [comment]
> This can be solved via configuring .mailmap manually, but I don't know which email is their main email.

Only one name would appear in the Acknowledgements  section of LKMPG. No email address is shown except me (as the maintainer).

**Comment by fennecJ** [comment]
> Only the preferable name would appear in the Acknowledgements section of LKMPG. No email address is shown except me (as the maintainer).

I know, the reason why I wanted to know the main mail of contributors is that I want to maintain the list as the example source 
code you mentioned before (https://github.com/oetiker/lshort/blob/master/book/src/contrib.tex).
Which is in the format of
Name,       % Email
Where the % causes latex ignore the info after it.

I can also make scripts to generate the list as you said, that is
```
Name (to be listed in LKMPG)[, Hanyu Pinyin], email-1[, email-2][, email 3][, remark (usually GitHub account)]
```
Which puts different emails in the same line if they belong to the same name.
Then use another script to parse the list and generate the `contrib.tex`.
But I wonder how will we deal with the situation that two different contributors use the same name in commit logs.
If that thing happened, will we put their emails in the same line or another new line?

**Comment by jserv** [comment]
> But I wonder how will we deal with the situation that two different contributors use the same name in commit logs.
> If that thing happened, will we put their emails in the same line or another new line?

It implies that we have much stronger community at that time. We can then manipulate manually.
