### ISSUE TITLE
missing sudo before `rmmod` 

### ISSUE THREAD

**Issue by 2011eric** [sysprog21/lkmpg#8]
Chapter 0.4.5, page 14

```
# sudo insmod hello-5.ko mystring="bebop" myintArray=-1
myshort is a short integer: 1
myint is an integer: 20
mylong is a long integer: 9999
mystring is a string: bebop
myintArray is -1 and 420

# rmmod hello-5
Goodbye, world 5
```

Should it  be `sudo rmmod hello-5` for consistency?

**Comment by jserv** [comment]
Please send a pull request to improve the usage.

**Comment by asas1asas200** [comment]
Conventionally, the `#` sign means it is login as root, and `$` sign means normal user session.

**Comment by 2011eric** [comment]
I know, but the problem here is about consistency,
like this:
```
# insmod hello-5.ko mystring="bebop" myintArray=-1
# rmmod hello-5
```
