### ISSUE TITLE
CI: Use static analysis tools to verify the code

### ISSUE THREAD

**Issue by jserv** [sysprog21/lkmpg#99]
Generally speaking, C programming language is not meant to be safety oriented, and we usually rely on extra static analysis tools to verify the code. For Linux kernel, [Sparse](https://www.kernel.org/doc/html/latest/dev-tools/sparse.html) is integrated into build systems. In addition, [Cppcheck](https://cppcheck.sourceforge.io/) is a neat tool to perform static analysis.

We can extend the existing CI pipeline to verify these examples before the built kernel modules are inserted into Linux.

Reference: [Assignment 3 - Software RAID](https://linux-kernel-labs.github.io/refs/heads/master/so2/assign3-software-raid.html)

**Comment by jserv** [comment]
Close via #105 and #106

**Comment by fennecJ** [comment]
I checked the newest workflow, and it shows the following:
![image](https://user-images.githubusercontent.com/58484289/134503877-96802efc-a1fc-46d5-ab72-5eb592159197.png)

I am not familiar with sparse, shall we install `gtk2/gtk3` and `llvm` in docker or just ignore these 2 lines ?

**Comment by jserv** [comment]
> I checked the newest workflow, and it shows the following:
> ![image](https://user-images.githubusercontent.com/58484289/134503877-96802efc-a1fc-46d5-ab72-5eb592159197.png)
> 
> I am not familiar with sparse, shall we install `gtk2/gtk3` and `llvm` in docker or just ignore these 2 lines ?

`sparse` can be built without GTK and LLVM. Let's keep the minimal build for CI pipeline.
